### ISSUE TITLE
Melhoramento: Readme sem informações!

### ISSUE THREAD

**Issue by JonasUliana** [anhaxteam/Apache-Virtual-Hosts#1]
O script pode ter um potêncial imenso, porém com a *descrição atual*, não vai chamar atenção de muita gente! Seria interessante uma **wiki** ou um README descrevendo melhor o script.

**Comment by JoaoArtur** [comment]
Claro Uliana! Ainda não fiz o README com paciência devido às minhas condições atuais (férias + 3g) hahah, mas logo irei fazer direitinho como nos outros projetos.
Valeu pelo comment!

**Comment by JoaoArtur** [comment]
Opa Uliana, tranquilo? Passei aqui só para avisar que dei uma atualizada no README e publiquei uma nova versão da ferramenta ja... continuo fazendo alterações nela.
